name: Azure Storage Account CI/CD

env:
  STORAGE_ACCOUNT_NAME: iapsalbp
  CDN_PROFILE_NAME: IAP-SA-LBP-CDN
  CDN_ENDPOINT: IAP-SA-LBP-CDN
  RESOURCE_GROUP: InsurAceProduction

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build project
      run: |
        npm ci
        npm run build

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_STORAGE_ACCOUNT_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az storage blob upload-batch --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --destination '$web' --source ./dist

    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az cdn endpoint purge --content-paths '/*' --profile-name ${{ env.CDN_PROFILE_NAME }} --name ${{ env.CDN_ENDPOINT }} --resource-group ${{ env.RESOURCE_GROUP }} --no-wait

    # Azure logout
    - name: Logout
      run: |
        az logout
